name: Linter Continuous Integration

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Lint code
        uses: ./.github/actions/frontend/run-eslint
      - name: Kommentiere PR
        uses: actions/github-script@v6
        with:
          script: |
            
            const fs = require('fs')
            
            fileText = fs.readFileSync('./pab/output.txt').toString('utf-8')
            if(fileText === ""){
              fileText = "All files pass linting"
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fileText
            })
