CREATE TABLE [dbo].[C_Lohnart](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Konto] [varchar](5) NOT NULL,
	[Bezeichnung] [varchar](80) NOT NULL,
 CONSTRAINT [PK_C_Lohnart] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];