INSERT INTO Mitarbeiter (PersonalNr,
                         Anrede,
                         Nachname,
                         Vorname,
                         Kurzname,
                         Geschaeftsstelle,
                         eMail,
                         IstIntern,
                         IstAktiv,
                         ZuletztGeaendertAm,
                         ZuletztGeaendertVon,
                         SachbearbeiterID,
                         MitarbeiterTypID,
                         Eintrittsdatum,
                         Austrittsdatum)
VALUES (9999,
        'Herr',
        'Test',
        'Test',
        'Tst',
        'Münster',
        'test@viadee.de',
        1,
        1,
        GETDATE(),
        'Tst',
        (SELECT TOP(1) ID FROM Mitarbeiter),
        1,
        '2018-01-01',
        '2099-01-01');