CREATE TABLE [dbo].[C_BuchungstypUrlaub](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Bezeichnung] [varchar](80) NOT NULL,
 CONSTRAINT [PK_C_BuchungstypUrlaub] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];